# Generated by Django 5.2.7 on 2025-11-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name="Nom de l'ingrédient")),
                ('categorie', models.CharField(choices=[('legume', 'Légume'), ('fruit', 'Fruit'), ('viande', 'Viande'), ('poisson', 'Poisson'), ('epice', 'Épice'), ('laitier', 'Laitier'), ('feculent', 'Féculent')], default='legume', max_length=30, verbose_name='Catégorie alimentaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ingrédient',
                'verbose_name_plural': 'Ingrédients',
                'ordering': ['nom'],
            },
        ),
    ]
