# Generated by Django 5.2.7 on 2025-11-10 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'verbose_name_plural': 'Ingredients de la recette'},
        ),
    ]
